### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "apsara",
  "email": "apsara@example.com",
  "address": "123 perrsh street",
  "dateOfBirth": "1995-06-07",
  "registeredDate": "2024-10-12"
}

###